# 留给后人：
# 掌邮的依赖建议每隔一年就升级一次，对于升级的方式有以下两种：
## 1、Gradle Dependency Updates 插件
# AS 下载 Gradle Dependency Updates 插件，插件主页：https://plugins.jetbrains.com/plugin/14243-gradle-dependency-updates
#
# 该插件会自动检查所有模块的依赖版本，比较智能
#
## 2、手动查询
# - 每个依赖我都贴心的给出了官网地址，可以快速查到最新版本号
# - 也可以在该网站中寻找到所有仓库的依赖：https://mvnrepository.com/
#
#  注意：
# - 如果你要添加其他依赖，请贴出官网地址，方便后人查找
# - 依赖一定要经常升级，不然到后面一起升很麻烦
#
# @author 985892345
# @date 2024/11/17 18:52


[versions]
javaTarget = "17"
kotlinJvmTarget = "17"
####################################################################################################
#                                            Android
####################################################################################################
# https://developer.android.com/build/releases/gradle-plugin?hl=zh-cn
agp = "9.3.1"
android-compileSdk = "37"
android-minSdk = "26"
android-targetSdk = "37"
# https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-appcompat = "1.7.1"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle = "2.11.0"
# https://developer.android.com/jetpack/androidx/releases/core
androidx-core-ktx = "1.19.0"
# https://developer.android.com/jetpack/androidx/releases/core
androidx-core-animation = "1.0.0"
# https://developer.android.com/kotlin/ktx/extensions-list#androidxcollection
androidx-collection-ktx = "1.6.0"
# https://developer.android.com/jetpack/androidx/releases/fragment
androidx-fragment = "1.8.9"
# https://developer.android.com/jetpack/androidx/releases/activity
androidx-activity = "1.13.0"
# https://developer.android.com/jetpack/androidx/releases/paging
androidx-paging = "3.5.0"
# https://developer.android.com/jetpack/androidx/releases/room
androidx-room = "2.8.4"
# https://developer.android.com/jetpack/androidx/releases/work
androidx-work = "2.11.2"

####################################################################################################
#                                              控件
####################################################################################################
# https://developer.android.com/jetpack/androidx/releases/constraintlayout
androidx-constraintlayout = "2.2.2"
# https://developer.android.com/jetpack/androidx/releases/recyclerview
androidx-recyclerview = "1.4.0"
# https://developer.android.com/jetpack/androidx/releases/cardview
androidx-cardview = "1.0.0"
# https://developer.android.com/jetpack/androidx/releases/viewpager2
androidx-viewpager2 = "1.1.0"
# https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout
androidx-swiperefreshlayout = "1.2.0"
# https://github.com/material-components/material-components-android
material = "1.14.0"
# https://github.com/google/flexbox-layout
flexbox = "3.0.0"
# https://lottiefiles.com/blog/working-with-lottie/getting-started-with-lottie-animations-in-android-app
# 最新版本号请查看：https://mvnrepository.com/artifact/com.airbnb.android/lottie
lottie = "6.7.1"
# https://github.com/Baseflow/PhotoView
# 查看图片的控件，支持双指缩放，但最后更新是 17 年
photoView = "2.3.0"
# https://github.com/985892345/NetLayout
# 20 级郭祥瑞封装的课表底层控件，如果有问题，欢迎来联系 👀
netLayout = "1.1.2"
# https://github.com/985892345/SlideShow
# 20 级郭祥瑞封装的 Banner 库，如果有问题，欢迎来联系 👀
slideShow = "2.0.1"
# https://github.com/scwang90/SmartRefreshLayout
smartRefreshLayout = "3.0.0-alpha"
# https://github.com/afollestad/material-dialogs
dialog = "3.3.0" # 作者已停止维护
# https://github.com/AigeStudio/WheelPicker
# 一个滚轮选择器
wheelPicker = "1.1.3"
# https://github.com/wangjiegulu/WheelView
# 又一个滚轮选择器（为什么会有多个？我也不知道，但这个 17 年后就没维护了）
wheelView = "4.1.15"

####################################################################################################
#                                              Kotlin
####################################################################################################
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.4.10"
# https://github.com/google/ksp/releases
ksp = "2.3.10" # KSP 2.3 起版本不再与 Kotlin 编译器版本绑定，但升级工具链时仍需验证兼容性
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.11.0"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinx-collections = "0.5.1"
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = "1.11.0"
# https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = "0.8.0"
# https://github.com/Kotlin/kotlinx-atomicfu
kotlinx-atomicfu = "0.33.0"
# https://github.com/ktorio/ktor
ktor = "3.5.1"
########################################### KMP 第三方依赖 ###########################################
# https://github.com/eygraber/uri-kmp
kmp-uri = "0.0.21"
# https://github.com/985892345/KtProvider
kmp-ktProvider = "1.5.0" # 985892345 的 kt 多平台跨模块服务提供框架
# https://github.com/russhwolf/multiplatform-settings
kmp-settings = "1.3.0"
# https://github.com/Foso/Ktorfit
kmp-ktorfit = "2.7.5"


####################################################################################################
#                                              Compose
####################################################################################################
# https://github.com/JetBrains/compose-multiplatform/releases
compose-multiplatform = "1.11.1"
# 官网文档可能更新不及时，版本请看 compose 发布时给出的版本
compose-navigation3 = "1.1.1"
# https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-lifecycle.html
# 看 compose 发布时给出的版本
compose-lifecycle = "2.11.0"
# 看 compose 发布时给出的版本
compose-savedstate = "1.4.0"
# 看 compose 发布时给出的版本
compose-material-icons = "1.7.3"
# 看 compose 发布时给出的版本
compose-adaptive = "1.3.0-alpha07"
# 多平台版本，非官方 https://github.com/Lavmee/constraintlayout-compose-multiplatform
compose-constraintLayout = "0.7.0"
# 官方约束布局，但只有安卓版本 https://developer.android.com/jetpack/androidx/releases/constraintlayout
compose-constraintLayout-android = "1.1.2"
# https://github.com/alexzhirkevich/compottie
compose-lottie = "2.2.4"

####################################################################################################
#                                               三方库
####################################################################################################
# https://developer.umeng.com/docs/67966/detail/206987
umeng-common = "9.9.6"
umeng-asms = "1.8.7.2"
umeng-push = "6.7.6"
# https://github.com/Tencent/VasDolly
vasdolly = "3.0.6"
# 具体a参考自官方文档 https://bugly.qq.com/v2/index
# 其中掌邮接入了 异常上报 和 应用升级 两个功能，注意看完官网文档
bugly = "4.1.9.3"
# https://github.com/greenrobot/EventBus
eventBus = "3.3.1"
# https://github.com/bumptech/glide/releases
glide = "5.0.9"
# https://github.com/Yalantis/uCrop
# 一个裁剪图片的库
ucrop = "2.2.11-native"
# https://github.com/square/retrofit
retrofit = "3.0.0"
# https://github.com/square/okhttp
okhttp = "5.4.0"
# https://github.com/google/gson
gson = "2.14.0"
# https://github.com/ReactiveX/RxJava
rxjava = "3.1.12"
# https://github.com/ReactiveX/RxAndroid
rxjava-android = "3.0.2"
# https://github.com/ReactiveX/RxKotlin
rxjava-kotlin = "3.0.1"
# https://github.com/tbruyelle/RxPermissions
rxpermissions = "v0.12" # 作者 20 年已停止维护
# https://github.com/square/leakcanary
leakcanary = "2.14"
# https://www.wanandroid.com/blog/show/2526
# https://github.com/whataa/pandora
pandora = "androidx_v2.1.0"
# 字节很好用调试工具 https://github.com/bytedance/CodeLocator
codelocator = "2.0.4"
# https://github.com/square/kotlinpoet
kotlinpoet = "2.3.0"
# kmp大图浏览 https://github.com/jvziyaoyao/scale
scale = "1.1.1-beta.3"
# coil kmp网络图片加载框架 https://github.com/coil-kt/coil
coil = "3.5.0"
# filekit 跨平台的文件操作三方库 https://github.com/vinceglb/FileKit
filekit = "0.14.2"
# 文件操作库 https://github.com/square/okio
okio = "3.18.1"
# 权限申请的第三方库 https://github.com/icerockdev/moko-permissions
moko-permissions = "0.20.1"
# 高德地图的定位 https://lbs.amap.com/api/android-location-sdk/guide/create-project/android-studio-create-project
amap = "11.2.000"
# 多平台 BuildConfig 生成 https://github.com/gmazzo/gradle-buildconfig-plugin
buildconfig = "6.0.10"

[libraries]
####################################################################################################
#                                              Android
####################################################################################################
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-reactivestreams-ktx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-animation = { module = "androidx.core:core-animation", version.ref = "androidx-core-animation" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

######################################## 特殊依赖，少量模块引入 ########################################
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-rxjava = { module = "androidx.paging:paging-runtime-rxjava3", version.ref = "androidx-paging" }
androidx-room = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-rxjava = { module = "androidx.room:room-rxjava3", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

####################################################################################################
#                                                控件
####################################################################################################
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
netLayout = { module = "io.github.985892345:NetLayout", version.ref = "netLayout" }
slideShow = { module = "io.github.985892345:SlideShow", version.ref = "slideShow" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
dialog = { module = "com.afollestad.material-dialogs:core", version.ref = "dialog" }
wheelPicker = { module = "cn.aigestudio.wheelpicker:WheelPicker", version.ref = "wheelPicker" }
wheelView = { module = "com.github.gzu-liyujiang.AndroidPicker:WheelView", version.ref = "wheelView" }
smartRefreshLayout = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "smartRefreshLayout" }
smartRefreshLayout-header-classics = { module = "io.github.scwang90:refresh-header-classics", version.ref = "smartRefreshLayout" }      # 经典刷新头
smartRefreshLayout-header-radar = { module = "io.github.scwang90:refresh-header-radar", version.ref = "smartRefreshLayout" }            # 雷达刷新头
smartRefreshLayout-header-falsify = { module = "io.github.scwang90:refresh-header-falsify", version.ref = "smartRefreshLayout" }        # 虚拟刷新头
smartRefreshLayout-header-material = { module = "io.github.scwang90:refresh-header-material", version.ref = "smartRefreshLayout" }      # 谷歌刷新头
smartRefreshLayout-header-two-level = { module = "io.github.scwang90:refresh-header-two-level", version.ref = "smartRefreshLayout" }    # 二级刷新头
smartRefreshLayout-footer-classics = { module = "io.github.scwang90:refresh-footer-classics", version.ref = "smartRefreshLayout" }      # 经典加载
smartRefreshLayout-footer-ball = { module = "io.github.scwang90:refresh-footer-ball", version.ref = "smartRefreshLayout" }              # 球脉冲加载

####################################################################################################
#                                               Kotlin
####################################################################################################
# gradlePlugin 找不到的话可以进 pom 文件进行查看：https://repo1.maven.org/maven2/org/jetbrains/kotlin/plugin/
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" } # 协程单测 runTest
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines" }                # 包含 Flow 与 Rxjava3 的互转
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-atomicfu-gradlePlugin = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "kotlinx-atomicfu" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
########################################### KMP 第三方依赖 ###########################################
kmp-uri = { module = "com.eygraber:uri-kmp", version.ref = "kmp-uri" }
kmp-settings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "kmp-settings" }
kmp-settings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "kmp-settings" }
kmp-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "kmp-settings" }
kmp-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "kmp-settings" }
kmp-ktProvider-gradlePlugin = { module = "io.github.985892345:provider-plugin-gradle", version.ref = "kmp-ktProvider" }
kmp-ktProvider-manager = { module = "io.github.985892345:provider-manager", version.ref = "kmp-ktProvider" }
kmp-ktProvider-api = { module = "io.github.985892345:provider-api", version.ref = "kmp-ktProvider" }
kmp-ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib-light", version.ref = "kmp-ktorfit" }
kmp-ktorfit-gradlePlugin = { module = "de.jensklingenberg.ktorfit:de.jensklingenberg.ktorfit.gradle.plugin", version.ref = "kmp-ktorfit" }

####################################################################################################
#                                              Compose
####################################################################################################
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
compose-compiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-navigation3 = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "compose-navigation3" }
compose-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "compose-adaptive" }
compose-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "compose-adaptive" }
compose-adaptive-navigation3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "compose-adaptive" }

compose-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "compose-lifecycle" }

compose-savedstate = { module = "org.jetbrains.androidx.savedstate:savedstate", version.ref = "compose-savedstate" }

compose-constraintLayout = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version.ref = "compose-constraintLayout" }
compose-constraintLayout-android = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintLayout-android" }
compose-lottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compose-lottie" }

####################################################################################################
#                                               三方库
####################################################################################################

######################################## 特殊依赖，少量模块引入 ########################################
umeng = { module = "com.umeng.umsdk:common", version.ref = "umeng-common" }
umeng-asms = { module = "com.umeng.umsdk:asms", version.ref = "umeng-asms" }
umeng-push = { module = "com.umeng.umsdk:push", version.ref = "umeng-push" } # 友盟的 push 真能用吗？
vasdolly = { module = "com.tencent.vasdolly:helper", version.ref = "vasdolly" }
vasdolly-gradlePlugin = { module = "com.tencent.vasdolly:plugin", version.ref = "vasdolly" }
bugly-crash = { module = "com.tencent.bugly:crashreport", version.ref = "bugly" }
ucrop = { module = "com.github.Yalantis:uCrop", version.ref = "ucrop" }                                 # 图片裁剪
rxpermissions = { module = "com.github.tbruyelle:RxPermissions", version.ref = "rxpermissions" }        # 权限申请
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }      # 内存泄漏
pandora = { module = "com.github.whataa:pandora", version.ref = "pandora" }         # 很牛逼的 debug 检测工具，debug 模式下摇一摇手机或者按三次手机中间顶部区域触发
codeLocator-core = { module = "com.bytedance.tools.codelocator:codelocator-core", version.ref = "codelocator" }
kotlinpoet = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
scale-sampling-decoder = { module = "com.jvziyaoyao.scale:sampling-decoder", version.ref = "scale" }
scale-image-viewer = { module = "com.jvziyaoyao.scale:image-viewer", version.ref = "scale" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
moko-permissions = {module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions"}
moko-permissions-location = {module = "dev.icerock.moko:permissions-location", version.ref = "moko-permissions"}
amap-location = { module = "com.amap.api:location", version.ref = "amap" }
####################################### 公有依赖，大部分模块使用 #######################################
eventBus = { module = "org.greenrobot:eventbus", version.ref = "eventBus" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinxSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
retrofit-adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxjava-android = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxjava-android" }
rxjava-kotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxjava-kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidMultiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAtomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlinx-atomicfu" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
vasdolly = { id = "com.tencent.vasdolly" }
ktProvider = { id = "io.github.985892345.KtProvider", version.ref = "kmp-ktProvider" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "kmp-ktorfit" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }

[bundles]
projectBase = [
    # Android 基础依赖
    "androidx-appcompat",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-process",
    "androidx-lifecycle-service",
    "androidx-lifecycle-reactivestreams-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-savedstate",
    "androidx-lifecycle-livedata-ktx",
    "androidx-core-ktx",
    "androidx-core-animation",
    "androidx-collection-ktx",
    "androidx-fragment-ktx",
    "androidx-activity-ktx",
    # Kotlin 基础依赖
    "kotlinx-coroutines",
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-rx3",
    "kotlinx-collections",
    # rxjava 所有模块都需要
    "rxjava",
    "rxjava-android",
    "rxjava-kotlin",
]

views = [
    "androidx-constraintlayout",
    "androidx-recyclerview",
    "androidx-cardview",
    "androidx-viewpager2",
    "androidx-swiperefreshlayout",
    "material",
    "flexbox",
]
